<?php
$cachedTables['cms_post']=[
	'id' => 'cms_post',
	'name' => '新闻',
	'is_default' => true,
	'note' => 'bbb',
	'back_action_index' => false,
	'back_action_create' => false,
	'back_action_update' => false,
	'back_action_delete' => false,
	'back_action_other' => false,
	'back_action_custom' => '',
	'front_action_channel' => false,
	'front_action_list' => false,
	'front_action_detail' => false,
	'front_action_search' => false,
	'front_action_index' => false,
	'front_action_create' => false,
	'front_action_update' => false,
	'front_action_delete' => false,
	'front_action_other' => false,
	'front_action_custom' => '',
];